### ISSUE TITLE
UDP errors on Windows

### ISSUE THREAD

**Issue by stunndard** [anacrolix/torrent#83] opened 2016-05-31 06:29 UTC
When running on Windows, after 1-2 minute of downloading, I get non stop error messages that keep scrolling infinitely. When I restart torrent, it works ok, but after 1 minute the same happens again.

![Screenshot](http://i.imgur.com/x57KFyC.png?1)

When I checked the network activity of the torrent process after the error kicks in, I find out that it "loses" all UDP connections and only TCP connections remain active.

![Screenshot](http://i.imgur.com/FJr5R3Y.png?1)

This might be an error in UDP socket implementation for Windows in the network libraries you're using. Or something else.

**Comment by anacrolix** [comment] 2016-06-01 02:15
Thanks for this. I don't do testing on Windows. This would occur if the UDP connection in use had been closed. It may be closed in some circumstances if there's an unexpected error in either DHT or uTP. Are you able to get the first few messages before this avalanche of "use of closed network connection"? The reason should be there. In the meanwhile I'll try to suppress the "use of closed network connection" error message as it's not useful.

**Comment by anacrolix** [comment] 2016-06-01 02:30
I've done some more poking. It's very likely that there's an unexpected read error from Windows in the uTP package, possibly a temporary error that needs to be handled, that triggers the uTP socket to be destroyed. This socket is shared with DHT, which doesn't expect this to happen. Let me know if you can find that first error message.

**Comment by anacrolix** [comment] 2016-06-01 02:32
What version of Go are you using?

**Comment by stunndard** [comment] 2016-06-01 03:14
This is the info about my system.
```
d:\work\src\Go\src\github.com\anacrolix\torrent\cmd>go version
go version go1.6.2 windows/amd64

d:\work\src\Go\src\github.com\anacrolix\torrent\cmd>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=d:\work\src\Go
set GORACE=
set GOROOT=d:\Devel\go
set GOTOOLDIR=d:\Devel\go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```
I will try to get the first UDP error and will let you know.

**Comment by stunndard** [comment] 2016-06-01 03:26
Is that it?
```
2016/06/01 11:19:42 client.go:408: read udp 0.0.0.0:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.
```

**Comment by stunndard** [comment] 2016-06-01 04:01
https://lists.freedesktop.org/archives/nice/2014-October/000968.html

The error seems to be Windows specific and related to the TTL value set for the UDP socket. On my machinge (Windows 7) TTL is 64. I will try to modify the TTL (if Go allows it) for the UDP socket and will let you know how it goes.

**Comment by stunndard** [comment] 2016-06-01 07:16
I did some debugging. It's not related to TTL at all.
I've added some debug prints to utp/socket.go:

Here you're creating the udp listening socket:
```Go
func NewSocket(network, addr string) (s *Socket, err error) {
	if network == "" {
		network = "udp"
	}
	pc, err := listenPacket(network, addr)
	if err != nil {
		return
	}

        // aded code
	ptrVal := reflect.ValueOf(pc)
	//fmt.Println(ptrVal)
	val := reflect.Indirect(ptrVal)
	//fmt.Println(val)
	//next line will get you the net.netFD
	fdmember := val.FieldByName("fd")
	//fmt.Println(fdmember)
	val1 := reflect.Indirect(fdmember)
	//fmt.Println(val1)
	netFdPtr := val1.FieldByName("sysfd")
	//fmt.Println(netFdPtr)
	fd := syscall.Handle(netFdPtr.Uint())
	fmt.Println("socket handle: ", fd)
```

Here you're closing socket (I think the main udp socket should NEVER be closed, as it's used for DHT and UTP?)

```Go
func (s *Socket) destroy() {
	delete(sockets, s)
	s.destroyed.Set()
	// TODO: Perhaps we should only Close the PacketConn if we created it
	// ourselves.
        // aded code
	fmt.Println("socket destroyed")
	ptrVal := reflect.ValueOf(s.pc)
	//fmt.Println(ptrVal)
	//log.Printf("ptrVal: %s", ptrVal)
	val := reflect.Indirect(ptrVal)
	//fmt.Println(val)
	//next line will get you the net.netFD
	fdmember := val.FieldByName("fd")
	//fmt.Println(fdmember)
	val1 := reflect.Indirect(fdmember)
	//fmt.Println(val1)
	netFdPtr := val1.FieldByName("sysfd")
	//fmt.Println(netFdPtr)
	fd := syscall.Handle(netFdPtr.Uint())
	fmt.Println("socket handle: ", fd)
```

This is the output:

```
d:\work\src\Go\src\github.com\anacrolix\torrent\cmd\torrent>torrent  ******.torrent
creating utp listen socket
socket handle:  192
TTL before:  128 <nil>
<nil>
TTL after:  255 <nil>
created utp listen socket
&{0xc082056178 map[] {<nil> false} map[] {<nil> false} {<nil> false} 0xc082030ae0 {{{0 0 <nil>} {<nil> false} <nil>} {{0 0 <nil>} {<nil> false} <nil>}} <nil>}
2016/06/01 14:50:53 tracker_scraper.go:38: error preparing announce to "http://retracker.local/announce": lookup retracker.local: getaddrinfow: No such host is known.
&{{0xc08202e600}}  socket destroyed
socket handle:  192
2016/06/01 14:51:49 client.go:412: read udp 0.0.0.0:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.
```

As we can see the socket handle (192) is the same. That socket should never be destroyed in func (s *Socket) destroy().

**Comment by stunndard** [comment] 2016-06-01 07:23
I've added panic to func (s *Socket) destroy() to trace where it's coming from. This is the result:

```
panic: socket destroyed

goroutine 19 [running]:
panic(0x863740, 0xc0868ed180)
        d:/Devel/go/src/runtime/panic.go:481 +0x3f4
github.com/anacrolix/utp.(*Socket).destroy(0xc0820ff520)
        d:/work/src/Go/src/github.com/anacrolix/utp/socket.go:537 +0x473
github.com/anacrolix/utp.(*Socket).reader(0xc0820ff520)
        d:/work/src/Go/src/github.com/anacrolix/utp/socket.go:176 +0x1a1
created by github.com/anacrolix/utp.NewSocketFromPacketConn
        d:/work/src/Go/src/github.com/anacrolix/utp/socket.go:116 +0x18e
```
So we can see destroy() is called from func (s *Socket) reader()

```Go
func (s *Socket) reader() {
	mu.Lock()
	defer mu.Unlock()
	defer s.destroy()
....
```
So the socket gets destroyed after each read? Of course, if it's a listening udp socket, and it's closed, all subsequent Accept() calls on that socket will fail. I don't understand why the socket is destroyed after each read here and why it works on Linux. If I comment defer s.destroy() there's no more error shown and I can see UDP connections active for the torrent process.

**Comment by anacrolix** [comment] 2016-06-01 08:00
The error you've shown is it. The cause appears to be ReadFrom errors that occur only on Windows, that aren't actually fatal. However any error returned from ReadFrom is currently treated as fatal in Socket.reader. Note that you've misinterpreted how Socket.reader works, it doesn't destroy after every read. Socket.destroy is called if Socket.reader returns, as it's assumed something unrecoverable has occurred. You're correct that this also destroyed the UDP connection used by DHT. The PacketConn should not be closed if the connection was not created inside uTP, but this is not the real issue. The real issue is that we must filter out errors from ReadFrom which do not indicate the connection is no longer usable. Since the only reason the socket would be closed is due to the caller that provided the original PacketConn closing it, my interim solution will be to ignore (or log) errors from ReadFrom in Socket.reader, unless Socket.Close has been explicitly called, in which case Socket.reader will return on error. Secondarily, the PacketConn will only be closed if it was created from within the utp packet, and not provided by an external source (as occurs when called from the torrent packet in NewClient). I'll issue a patch shortly. If you can try it out, it will be appreciated. I'm also trying to test on wine, as I have no Windows available to me.

**Comment by stunndard** [comment] 2016-06-01 10:19
Thanks for clarifying, now I get it. I tried to change the return from Socket.reader to continue, and there's no more this error. I will test your patch when it's done as well.

**Comment by anacrolix** [comment] 2016-06-01 12:44
I've pushed the change to the utp package. It's a quick fix but I believe it'll solve it for now.

**Comment by deranjer** [comment] 2017-09-26 00:33
Just an FYI, I'm getting a very similar error very randomly during my testing when adding torrents via magnet link.  Here is the output:
```
magnet:?xt=urn:btih:9f9165d9a281a9b8e782cd5176bbcc8256fd1871&dn=Ubuntu+16.04.1+LTS+Desktop+64-bit&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
Ubuntu 16.04.1 LTS Desktop 64-bit
Addingping
panic: read udp [::]:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.

goroutine 21 [running]:
github.com/anacrolix/go-libutp.(*Socket).packetReader(0xc0421191f0)
	C:/Users/deranjer/go/src/github.com/anacrolix/go-libutp/socket.go:92 +0x186
created by github.com/anacrolix/go-libutp.NewSocket
	C:/Users/deranjer/go/src/github.com/anacrolix/go-libutp/socket.go:60 +0x2ca

Process finished with exit code 2
```

**Comment by anacrolix** [comment] 2017-09-26 01:15
Do you want to try with the panic commented out, or changed to a `log.Print`?

**Comment by deranjer** [comment] 2017-09-26 21:24
`read udp [::]:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.
panic: interface conversion: net.Addr is nil, not *net.UDPAddr

goroutine 6 [running]:
github.com/anacrolix/go-libutp.netAddrToLibSockaddr(0x0, 0x0, 0x1, 0x95)
	C:/Users/deranjer/go/src/github.com/anacrolix/go-libutp/sockaddr.go:101 +0xb6
github.com/anacrolix/go-libutp.(*Socket).packetReader(0xc0420f72d0)
	C:/Users/deranjer/go/src/github.com/anacrolix/go-libutp/socket.go:95 +0xc7
created by github.com/anacrolix/go-libutp.NewSocket
	C:/Users/deranjer/go/src/github.com/anacrolix/go-libutp/socket.go:61 +0x2ca

Process finished with exit code 2`

**Comment by anacrolix** [comment] 2017-09-27 00:42
Sorry, and add a `continue`, after the new log line.

**Comment by anacrolix** [comment] 2017-09-27 00:51
It's awful that this is happening, but I'm not exposed to Windows systems so I can't guess what the correct solution is.

**Comment by stunndard** [comment] 2017-09-27 11:22
I guess you could rely on WSA* Winsock functions at least in the UDP library, instead of using standard Go's runtime ones.

**Comment by deranjer** [comment] 2017-10-15 15:58
With the continue it does keep working, this is the output, the "ping"s are from my websocket code pinging from the frontend to the backend...

```
read udp [::]:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the op
eration was in progress.
read udp [::]:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the op
eration was in progress.
ping
read udp [::]:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the op
eration was in progress.
read udp [::]:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the op
eration was in progress.
read udp [::]:50007: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the op
eration was in progress.
ping
ping
```

**Closed** 2017-10-22 05:09 UTC
Labels: help wanted, windows

**Comment by MrGlp** [comment] 2023-08-27 16:18
ths

**Comment by anacrolix** [comment] 2023-08-27 23:24
que?
