### ISSUE TITLE
Consider removing `opMu` from `torrent.Reader`

### ISSUE THREAD

**Issue by YenForYang** [anacrolix/torrent#553] opened 2021-08-28 00:07 UTC
https://github.com/anacrolix/torrent/blob/9b6e191b0a92aa5c67a1e90fbed5001e6ed273b4/reader.go#L39-L40

The convention I've seen in the Go standard is to not add concurrent access safety by default -- unless it's specifically part of the design (e.g. `map` vs `sync.Map`). Users can wrap `torrent.Reader` in their own struct with their own `sync.Mutex` to ensure `Read()/ReadContext()/Seek()` can be called safely from different threads. Keeping `opMu` in `torrent.Reader` adds unnecessary overhead for those who don't need thread-safety. I'll also add that `io.Reader` and `io.Seeker` aren't generally expected to be thread-safe.

Currently, it looks like `opMu` is used only by the `ReadContext()` and `Seek` methods.

**Comment by anacrolix** [comment] 2021-08-28 08:41
Good idea. Let me check in to it. I suspect it might be so because if the user races some operations it might break the Client silently.

**Comment by anacrolix** [comment] 2021-08-28 08:41
Also are you seeing some performance overhead due to the opMu?

**Comment by anacrolix** [comment] 2021-09-02 06:30
I agree that not making stuff concurrent-safe for the sake of it is a good practice. However I think opMu in torrent.reader is because Seeking while Reading does actually break some invariants in this case. It might be possible to restructure it so that reads persist at their current location (and you can thus also Read at different locations too, like you can with native FS), but that's a lot of extra complexity.

**Comment by anacrolix** [comment] 2021-09-09 12:26
I've taken another look and I believe that removing opMu is probably correct. But I can't work out why it was added in the first place.

**Comment by tsynik** [comment] 2021-09-10 06:26
> I've taken another look and I believe that removing opMu is probably correct. But I can't work out why it was added in the first place.

last versions of TorrServer work fine without opMu lock, there is also disabled break on if !r.responsive && !r.t.pieceComplete(pieceIndex(req.Index)) in available func (looks good for video streams on rewind/forward)

**Comment by YenForYang** [comment] 2021-09-10 09:10
Forgot I made this issue. As for whether there is overhead, I haven't measured or noticed any. But I have confirmed (the expected obvious results) that less calls to Read() with a bigger []byte slice is a heck of a lot more efficient than making more calls with smaller slices. 

I'd expect that `opMu` plays a role is slower Reading/Seeking, but to be honest I've been using the library with `opMu` removed with no issues concerning races for a while now. I just thought it might be time for it to be removed since it doesn't seem to have much use at all.

**Comment by tsynik** [comment] 2021-09-10 09:19
If we talk here about performance, TorrServer still uses old outdated torrent engine on release builds from 2019? because of it. All modern torrent releases which we tesed before were twice more slow in speed how it serves content from reader to client, some also produced higher CPU usage. I can't figure root cause of this performance drop. I's better on current @master, but still less than with this codebase: https://github.com/tsynik/torrent

**Comment by anacrolix** [comment] 2021-09-10 10:22
Thank you for this feedback, it's very helpful. I wonder why version 1.1.4 is the best for you. The reports about issues, what version of torrent was that with? If it was new than 1.28.0, could you try with 1.28.0? What are the issues, CPU?

**Comment by anacrolix** [comment] 2021-09-10 10:24
I did notice some huge performance improvements in my own usage with 175b826e738c76d1a96e435bc5396e054ca5796a. However some changes since may have erased that. You could try 175b826e738c76d1a96e435bc5396e054ca5796a and report how it is for you.

**Comment by tsynik** [comment] 2021-09-10 11:16
> Thank you for this feedback, it's very helpful. I wonder why version 1.1.4 is the best for you. The reports about issues, what version of torrent was that with? If it was new than 1.28.0, could you try with 1.28.0? What are the issues, CPU?

Our 1st attempts to use "new" engine were with TorrServe v1.1.x in march 2020, so it was around **v1.15.2-v1.16.0**. Old engine have DHT connections spam and we tried to eliminate it. All builds have huge performance degradation not in downloading torrents but on serve ready blocks from RAM to client (player). Video torrents even about 20GB was not played smooth so we revert to working tree. 2nd attempt was with TorrServe MatriX (v1.2.x) on its 1st betas in march 2021 and with torrent **v1.25.1 - v1.26** - we saw similar performance issues as before. Users made some investigation with wget torrent stream from http to /dev/null and found that on old engine it reach for example 300-400Mbit/s and on new one not reach even 100 Mbit's with exactly the same torrent and TorrServer codebase (and it was not download issue because torrserver show memcache stae in web gui and there was preloaded data available it both cases). So, we reverted to old codebase. With TorrServer releases v101-v103 we again used current torrent, so it was torrent **v1.29.1-v1.29.2** - it's performance was better than we saw before and suitable to most content (but we again tested http serve to /dev/null with wget on gigabit link and comparing to old engine DL/read was around 150-220 Mbit/s vs 200-400 Mbit/s with old engine, and some users report they can't play those high bitrate torrents (Avatar 101GB with 80 Mbit/s average) which they played before switch to new release). I also saw 100+% cpu load on one core with v103 and it was 20-40% more than with same content/bitrate/version build with old engine. So TorrServer MatriX v104 was again with old engine (but with dht v2 backport and some actual code) and with new torrent (v1.30.2+) as an optional build. Users reported it's not so good as release. But, I also made test builds with new engine (v1.31.0) and users reported it works fine  ;-) And with current trunk it even better as before  ;-)

**Comment by anacrolix** [comment] 2021-09-10 22:18
Thank you. Damn I wish I know what the cause might be. It's very hard to set up tests for this because it depends heavily on use case, storage implementation, and real world peer interactions. Profile files of all kinds, with a specific revision of TorrServer attached would help, assuming I can figure out the revision of various anacrolix repos from TorrServer.

**Comment by anacrolix** [comment] 2021-09-10 22:20
Let's continue any performance discussion, in a GitHub discussion, or issue for specific profiles.

The original issue here has been addressed in master.

**Closed by anacrolix** 2021-09-10 22:20 UTC
