### ISSUE TITLE
panic: -1 github.com/anacrolix/torrent.(*PeerConn).deleteRequest

### ISSUE THREAD

**Issue by cutegirllml** [anacrolix/torrent#427] opened 2020-10-15 07:01 UTC
panic: -1
	panic: -1

goroutine 10852 [running]:
github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc002404e00, 0x5800000000000, 0xc000004000, 0xc0000b27e0)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/peerconn.go:1391 +0x374
github.com/anacrolix/torrent.(*PeerConn).deleteAllRequests(0xc002404e00)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/peerconn.go:1404 +0xa3
github.com/anacrolix/torrent.(*Torrent).deleteConnection(0xc0011a4700, 0xc002404e00, 0x0)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/torrent.go:1204 +0xc9
github.com/anacrolix/torrent.(*Torrent).dropConnection(0xc0011a4700, 0xc002404e00)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/torrent.go:1223 +0x5e
panic(0xa96600, 0xc001b728d8)

github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc002404e00, 0x5400000000000, 0xc000004000, 0xc0025a6f48)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/peerconn.go:1391 +0x374
github.com/anacrolix/torrent.(*PeerConn).receiveChunk(0xc002404e00, 0xc001c36380, 0x5, 0x1)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/peerconn.go:1196 +0x198
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc002404e00, 0x0, 0x0)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/peerconn.go:1039 +0x49c
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc000160000, 0xc002404e00, 0xc0011a4700)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/client.go:880 +0x5c7
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc000160000, 0xc0011a4700, 0xc61060, 0xc000eb2740, 0xb80315, 0x2, 0x0)
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/client.go:711 +0x2f4
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	/home/work/project/pkg/mod/github.com/anacrolix/torrent@v1.15.2/torrent.go:1752 +0x1f2
exit status 2

The process panic when I download two or more torrent files, but I don't know why?

**Comment by anacrolix** [comment] 2020-10-15 23:39
I believe this is a duplicate of https://github.com/anacrolix/torrent/issues/388. This issue was pinned. The fix is available in v1.16.0 onwards.

**Closed by anacrolix** 2020-10-15 23:39 UTC
