### ISSUE TITLE
How to create a torrent without top directory?

### ISSUE THREAD

**Issue by kyoto44** [anacrolix/torrent#468] opened 2021-02-21 10:15 UTC
Hello! I've got a problem with torrent creation. If I'm specifying "Name" field in metainfo.Info then it becomes the name of top directory if not I'm getting "_" as top directory

**Comment by anacrolix** [comment] 2021-02-21 23:16
Are you using the `metainfo` package, or `cmd/torrent-create` or something else?

**Comment by kyoto44** [comment] 2021-02-22 03:34
I'm using metainfo package

**Comment by not-duckie** [comment] 2021-02-22 06:21
can you post the code, please @kyoto44

**Comment by kyoto44** [comment] 2021-02-22 07:24
> can you post the code, please @kyoto44

```
mi := metainfo.MetaInfo{
			AnnounceList: builtinAnnounceList,
		}

		mi.SetDefaults()
		info := metainfo.Info{
			PieceLength: 256 * 1024,
			Name:        filepath.Base(filePath),
		}
		mi.UrlList = []string{webseedURL}

		file, _ := os.Open(filePath)
		fi, _ := file.Stat()
		info.Files = append(info.Files, metainfo.FileInfo{
			Path:   []string{filepath.Base(filePath)},
			Length: fi.Size(),
		})

		err := info.GeneratePieces(func(fi metainfo.FileInfo) (io.ReadCloser, error) {
			return os.Open(filePath)
		})
		if err != nil {
			log.Errorf("error generating pieces: %s", err)
		}
		mi.InfoBytes, err = bencode.Marshal(info)
		if err != nil {
			log.Error(err)
		}

		f, err := os.Create("/home/kyoto44/torrents/" + filepath.Base(filePath) + ".torrent")
		if err != nil {
			log.Error(err)
		}
		defer f.Close()

		err = mi.Write(f)
		if err != nil {
			log.Error(err)
		}
```

**Comment by kyoto44** [comment] 2021-02-24 20:46
Is there any solution?

**Comment by anacrolix** [comment] 2021-02-25 15:51
Sorry I still don't have enough information. The snippet of code you gave should generate a metainfo. Does that metainfo contain "_" for the Name field, or do you get a "_" directory when you download with this using a file-based storage with the torrent Client in this repo?

**Comment by kyoto44** [comment] 2021-02-25 18:52
@anacrolix, it generates. But if I set an empty Name field the torrent file structure looks like this
![image](https://user-images.githubusercontent.com/17720761/109202166-7f6bd200-77c4-11eb-8519-c96b7b01b832.png)

**Comment by anacrolix** [comment] 2021-03-01 02:58
When I run torrent-create without setting the Info.Name, I get an empty name field in the resulting metainfo. Are you getting the `_` directory when you then pass a metainfo to a torrent client? If so, and you're passing it to a client based on this repo, which file storage are you using?

**Comment by anacrolix** [comment] 2021-03-01 03:11
I cannot reproduce, even when trying to download with the file, and mmap storage backends.

**Comment by kyoto44** [comment] 2021-03-01 05:33
> I cannot reproduce, even when trying to download with the file, and mmap storage backends.

just use my code from above

**Comment by kyoto44** [comment] 2021-03-01 05:35
> When I run torrent-create without setting the Info.Name, I get an empty name field in the resulting metainfo. Are you getting the `_` directory when you then pass a metainfo to a torrent client? If so, and you're passing it to a client based on this repo, which file storage are you using?

Yes, I'm getting `_` directory when I pass torrent to any torrent client. What should i do to create torrent without any directories in it???

**Comment by anacrolix** [comment] 2021-03-01 09:17
The client in this repo does not create any `_` directory, so you could use that. Try `cmd/torrent`. I will preemptively close this issue since there's nothing actually wrong here.

**Closed by anacrolix** 2021-03-01 09:17 UTC
