### ISSUE TITLE
Improve start-up efficiency when hashing with file-based storage backends

### ISSUE THREAD

**Issue by zhulik** [anacrolix/torrent#50] opened 2015-12-23 00:52 UTC
Hi, i built some torrent downloader based on you package. 

When i tryed to download big torrent (about 15GB), i noticed, that memory usage is really great (about 700MB), CPU usage about 80-90% on one core. htop shows me large number of downloader threads (50 at least) and it's increases. 

At about 15% of downloading i see that messages in logs:
`2015/12/23 08:03:00 error writing chunk: open <path to one of files>: too many open files`

My wrapper around your package is small and thin and can't produce described problems. You can find it [here](https://github.com/zhulik/go_torrent_bot)

It is your bugs or it is my fault and i should play with packge config/tuning go runtime?

For example, transmission-web uses about 100MB of memory and 20-30% of one CPU core with 50 seeding torrents and 1-2 active downloads.

I am newbie in go development and not familiar with golang's profilers, but i want to learn it. I will try to debug this problems in the next few days.

Thanks and sorry for my english!

**Comment by anacrolix** [comment] 2015-12-23 00:56
Thanks for the report. I believe the cause is the way I offload writes to disk which can be too slow for a fast torrent. If you're using a wrapper, could you try the mmap backed data store as an alternative? I'll address the too many open files issue soon. Thanks.

**Comment by zhulik** [comment] 2015-12-23 09:01
`If you're using a wrapper, could you try the mmap backed data store as an alternative?`

Can you explain?

**Comment by anacrolix** [comment] 2015-12-24 14:43
In your code at https://github.com/zhulik/go_torrent_bot/blob/master/main.go#L34, you can set TorrentDataOpener to the mmap.TorrentData backend, an example is here in the tests: https://github.com/anacrolix/torrent/blob/master/fs/torrentfs_test.go#L206. This avoids using Open/Close and file handle overhead. Let me know if it's still a problem with this.

**Comment by zhulik** [comment] 2015-12-24 21:53
Hi, i hade updated torrent package, set mmap.TorrentData as you told me. 
I see, that memory usage still high, htop shows about 500MB, stable.
CPU usage is high too: 100% of first core + 30-50% of second.

Positive changes: i don't see large numbers of threads, just 7, but on 80% of downloading it was increased to 32. Dowloaded files are valid, no too many open files errors.

Negative:
`2015/12/25 08:25:58 Failed to get updates, retrying in 3 seconds...` in logs after downloading

After downloading, i still have 100% cpu usage by kswap0 process, it is common problem in linux, but no one of founded solutions doesn't work for me(maybe problem in kernel, i have old 4.1.6 on target machine, mayby your mmap realization does something wrong with it)

After killing downloader kswap0 process calmed down

**Comment by anacrolix** [comment] 2015-12-25 02:27
That log message is not originating from the torrent package. Perhaps
something else is going on.

**Comment by zhulik** [comment] 2015-12-25 08:48
Sorry, you answered on old version of comment. I have updated it. Please, read it from web.

**Comment by zhulik** [comment] 2015-12-25 20:10
Here is my cpu profile. I have no experience in reading go's profiles, but i suppose, that crypto/sha1.block is slow. Am i right?
[cpu.pdf](https://github.com/anacrolix/torrent/files/72254/cpu.pdf)

**Comment by anacrolix** [comment] 2015-12-26 00:42
Thanks. How large is the torrent you're downloading? Are you using the file or mmap data backend? What OS/architecture are you using?

**Comment by zhulik** [comment] 2015-12-26 10:52
I was downloading many torrents about 15-20Gb, all of them has the same client behavior. 

Client initialization you can find [here](https://github.com/zhulik/go_torrent_bot/blob/master/main.go#L37), mmap storage. OS: ArchLinux latest, x86_64, 100Mbit internet connection, transmission shows me ~5-7 Mb/s speed

**Comment by zhulik** [comment] 2015-12-26 14:25
I just configured newrelic monitoring and then download 20Gb torrent. There is graphs
![2015-12-26 18-20-50](https://cloud.githubusercontent.com/assets/287062/12006773/51d8b81c-abf5-11e5-849b-aea5ac595260.png)
![2015-12-26 18-21-00](https://cloud.githubusercontent.com/assets/287062/12006772/51d86e7a-abf5-11e5-9261-493e535dce06.png)
![2015-12-26 18-21-07](https://cloud.githubusercontent.com/assets/287062/12006775/523ea898-abf5-11e5-99a0-9cf04085ea9f.png)
![2015-12-26 18-21-15](https://cloud.githubusercontent.com/assets/287062/12006774/51dac418-abf5-11e5-8c5d-f5343b9ff926.png)

1400 active goroutins while downloading is really great amont. Scheduling of them is not free. Maybe, decreasing it is a good idea?

**Comment by anacrolix** [comment] 2015-12-28 02:15
So the cause is that on startup, torrent scans pieces from all files for the mmap and file backends rehashes them all. I moved onto using the pieces backend for my production purposes, and so those file-based backends haven't had enough attention. Some state between restarts is needed. On slow disks (I'm guessing spinning media)/CPU, and for large torrent, the rescan can be very expensive and take a while before the torrent can actually do anything else due to being starved for CPU. This can be confirmed by trying with small torrents and seeing they finish hashing first, or waiting out the hashing, and check that CPU drops and download speed picks up.

You can use the Client.WriteStatus to get a read out of what the torrent client is doing, you should see lots of pieces in the 'H' state, like 123H means 123 pieces are being hashed, when the CPU is up.

Let me know, and if you have any suggestions for where to maintain that state. I'm currently considering just a sqlite3 file in the directory that maps pieces to whether they've been checked before or something. Maybe like '.torrent.db'.

**Comment by 0x4139** [comment] 2016-01-14 14:08
Sorry to piggyback on the discussion, but it seems a bit ontopic.Can you give a small example on how to use the pieces backend?

**Comment by anacrolix** [comment] 2016-01-15 17:56
@0x4139 I put an example in the other issue.

**Comment by anacrolix** [comment] 2016-01-28 09:12
@zhulik Any update on your usage of this? Are you still having issues?

**Comment by anacrolix** [comment] 2016-06-20 07:52
I've started working on this.

**Comment by anacrolix** [comment] 2016-07-10 03:25
This was fixed in https://github.com/anacrolix/torrent/commit/d80d0db9d5b627bde04f29545f26174a3b9e21eb. There's a more recent bug fix to it in https://github.com/anacrolix/torrent/commit/11a53fa732406aea61681005773792aee211c4ad.

**Closed by anacrolix** 2016-07-10 03:25 UTC
