### ISSUE TITLE
large number of panics on v1.29.1

### ISSUE THREAD

**Issue by Nuke142** [anacrolix/torrent#545] opened 2021-08-13 09:54 UTC
Hey. I own a server on amd64 with a bunch of users, so i can provide logs with crashes if you interested.
[log.zip](https://github.com/anacrolix/torrent/files/6981514/log.zip)

**Comment by tsynik** [comment] 2021-08-13 22:20
another engine panic on v1.29.1 repored here: https://github.com/YouROK/TorrServer/issues/88

**Comment by anacrolix** [comment] 2021-08-14 10:16
Would you know the last version of anacrolix/torrent that didn't cause this? Is it only occuring for TorrServer?

**Comment by tsynik** [comment] 2021-08-14 10:34
TorrServer used old slightly modified torrent v1.2.6 before v100 release - https://github.com/YouROK/torrent/commits/master, so there is no such stats. In Nuke142 log panics mostly from those lines:

**Comment by anacrolix** [comment] 2021-08-15 02:07
Is it possible torrents are being Dropped while they are still in active use (downloading)? I think this might happen if attempts to write to storage occur after the Torrent has been dropped and connections are still reading.

**Comment by tsynik** [comment] 2021-08-15 08:11
> Is it possible torrents are being Dropped while they are still in active use (downloading)? I think this might happen if attempts to write to storage occur after the Torrent has been dropped and connections are still reading.

yes, it's possible. web server ui have drop button on it's front page, and torrent will be re-added if client (player) still request it. you can look a this server on http://free.tsarea.ru:8090

**Comment by anacrolix** [comment] 2021-08-16 01:13
Ok I suspect a unit test that drops torrents abruptly during transfers might make this reliably reproducible. The fix should be to check that the torrent is not closed, or that the storage still exists when writing a received chunk.

**Comment by tsynik** [comment] 2021-08-18 20:29
All fatal errors were eleminated in last TorrServer release with anacrolix@torrent anacrolix/torrent@v1.30.2, so probably you can close this issue.

2021/08/18 20:17:38 [Recovery] 2021/08/18 - 20:17:38 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:221 (0xafbf3df3)
/usr/local/go/src/runtime/signal_unix.go:735 (0xafc11e4b)
/Users/nikk/go/pkg/mod/github.com/anacrolix/torrent@v1.30.3-0.20210816011131-16176b762e4a/storage/wrappers.go:83 (0xafffeaac)
/Users/nikk/go/pkg/mod/github.com/anacrolix/torrent@v1.30.3-0.20210816011131-16176b762e4a/torrent.go:1268 (0xb01a6657)

still exists after drop torrent, but it's not fatal and can be ignored too

**Comment by anacrolix** [comment] 2021-08-18 23:27
FWIW, this obviously shouldn't panic, so please keep this issue open! What do you mean by fatal? Are you still seeing panics, but recovering them?

**Comment by tsynik** [comment] 2021-08-18 23:34
Yes, I still see such error for example when player accessed torrent and user changed server settings from web GUI (in that case server restart itself to apply new values. There is no server crash in that case - it's process stay alive.
Here is server's log from console - https://imgur.com/a/IeqggRP

**Comment by anacrolix** [comment] 2021-08-19 03:51
When you close the Torrent, are you closing any Readers on it, or any of its resources? These shouldn't panic, but probably would. There should also probably be a unit test for this. If this is the case, it should be quite easy to write tests for.

**Comment by YouROK** [comment] 2021-08-19 05:20
Struct of drops:
gotorrent drop -> cache close -> close all my reader -> in my reader closed gotorrent reader if torrent not dropped (actually in old gotorrent)
Verify of dropped torrent is 
```
 if len(r.file.Torrent().Files()) > 0 {
	r.Reader.Close()
}
```

**Comment by anacrolix** [comment] 2021-08-19 13:04
Just to clarify: You close torrent.Readers after their corresponding Torrents are Dropped. The Readers may be in use while the Torrents are Dropped. With earlier versions of anacrolix/torrent, this did not panic, but does with more recent versions?

**Comment by YouROK** [comment] 2021-08-19 13:09
Now I committed this line and not close readers of torrents

**Comment by anacrolix** [comment] 2021-08-20 03:04
Sorry I don't understand 😢 .

**Comment by tsynik** [comment] 2021-08-20 03:40
> Sorry I don't understand 😢 .

@YouROK probably told about this code change in TorrServer. https://github.com/YouROK/TorrServer/commit/399912c87ca32c1b40d76ab3e5d771b38d2d0fe2

**Comment by anacrolix** [comment] 2021-08-22 10:15
@Nuke142 per the OP: Most of the panics look to do with use of storage after it's been closed (read and write chunk). I wonder if the access pattern has changed with the changes in TorrServer, per @tsynik and @YouROK's changes. There is also a concurrent map access that looks like it's probably a bug in the TorrServer torrcache. There was also this one:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa990d7]

goroutine 2292783 [running]:
github.com/anacrolix/torrent.(*Torrent).pieceCompleteUncached(0xc0100a2a00, 0x1ecb, 0xc0e4911912)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.29.1/torrent.go:259 +0x57
github.com/anacrolix/torrent.(*Torrent).updatePieceCompletion(0xc0100a2a00, 0x1ecb, 0x1ecb)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.29.1/torrent.go:1236 +0x6f
github.com/anacrolix/torrent.(*Piece).UpdateCompletion(0xc0d607d538)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.29.1/piece.go:227 +0x85
server/torr/storage/torrstor.(*Piece).Release(0xc08b4e0190)
	/usr/src/torr/server/torr/storage/torrstor/piece.go:81 +0xc8
server/torr/storage/torrstor.(*Cache).removePiece(...)
	/usr/src/torr/server/torr/storage/torrstor/cache.go:117
server/torr/storage/torrstor.(*Cache).cleanPieces(0xc0850bb320)
	/usr/src/torr/server/torr/storage/torrstor/cache.go:196 +0x15d
created by server/torr/storage/torrstor.(*MemPiece).ReadAt
	/usr/src/torr/server/torr/storage/torrstor/mempiece.go:54 +0x229
```
This could be the torrcache accessing methods after the torrent is dropped.

**Comment by anacrolix** [comment] 2021-11-04 00:28
Could you try with v1.35.0? There have been lots of fixes throughout the storage code.

**Comment by anacrolix** [comment] 2021-11-11 06:13
Closing this as I don't think there's anything more that can be done.

**Closed by anacrolix** 2021-11-11 06:13 UTC

**Comment by Nuke142** [comment] 2021-11-11 06:17
Thank you. I see no crashes in 1.35.0

**Comment by anacrolix** [comment] 2021-11-12 04:03
Thank you for following up!
