### ISSUE TITLE
no public ip causing bep40PriorityBytes to panic

### ISSUE THREAD

**Issue by AlhasanIQ** [anacrolix/torrent#245] opened 2018-04-10 00:40 UTC
The panic fail-safe `bep40.go:71` is being called due to a.IP being nil.

Reason: on `client.go:1273`'s `firstNotNil()` returning nil due to both sides being nil.

i.e. `cl.config.PublicIp4` ,  `missinggo.AddrIP(cl.ListenAddr()).To4()` are nil.

Client info:
```
ListenAddr: "[::]:50007"
```

**Comment by anacrolix** [comment] 2018-04-10 03:07
Thanks, do you want to submit a test case and/or propose best behaviour?

**Comment by muesli** [comment] 2018-04-11 09:36
This seems to be a dupe of #244?

**Comment by anacrolix** [comment] 2018-04-11 11:01
It is a duplicate of #244.

**Closed by anacrolix** 2018-04-11 11:01 UTC
