### ISSUE TITLE
tls handshake failures with https trackers

### ISSUE THREAD

**Issue by f4nff** [anacrolix/torrent#276] opened 2018-10-14 18:22 UTC
Can only download the seeds of a single file，If there are multiple files in the seed, it cannot be downloaded.

**Comment by f4nff** [comment] 2018-10-14 18:30
test torrent

[2.torrent.zip](https://github.com/anacrolix/torrent/files/2476712/2.torrent.zip)

**Comment by f4nff** [comment] 2018-10-14 22:00
After my test, the client connects to the tracker. If it is https, it will fail and the peer information will not be obtained.
Https handshake has a bug


![image](https://user-images.githubusercontent.com/19538878/46922697-9cfacf80-d03f-11e8-8759-dd72da95cef6.png)

**Comment by anacrolix** [comment] 2018-10-15 03:32
I suspect it may be the TLS handshake host isn't the expected `opentracker.xyz` because the IP is resolved in advance for IP filtering purposes, and the IP is used in the header instead. I don't see a easy way to maintain the original TLS host in the http.Request struct.

**Comment by f4nff** [comment] 2018-10-15 04:34
@anacrolix 
The client I am using is 

> cmd/torrent

By capturing the package, I found that the first packet of the **torrent** is connected to the tls handshake of `https://opentracker.xyz:443/announce`, and the first package with the **chrome** connection `https://opentracker.xyz:443/announce` tls Is different。

![image](https://user-images.githubusercontent.com/19538878/46930174-a9e6e580-d076-11e8-8d94-9854fb0d21df.png)

![image](https://user-images.githubusercontent.com/19538878/46930180-b23f2080-d076-11e8-8fdc-df3df15d5c7e.png)
Can you solve him?

**Comment by anacrolix** [comment] 2018-10-15 04:43
Is Chrome the top image?

**Comment by f4nff** [comment] 2018-10-15 04:48
yes～

**Comment by f4nff** [comment] 2018-10-15 04:49
Using **torrent** is not able to properly request **https tracker**, `https://opentracker.xyz:443/announce`
But chrome is ok, you can grab a package and look at it.

**Comment by anacrolix** [comment] 2018-10-15 05:29
I still believe the problem is what I described in https://github.com/anacrolix/torrent/issues/276#issuecomment-429698192. I'll have to think about a solution.

**Comment by f4nff** [comment] 2018-10-15 05:47
Looking forward to your solution, you can try [tls1.3 ](https://github.com/cloudflare/tls-tris)golang

**Comment by f4nff** [comment] 2018-10-15 05:49
tracker `https://opentracker.xyz:443/announce`

```
    # The HTTP Header containing the IP address of the client.
    # This is only necessary if using a reverse proxy.
    real_ip_header: "X-Forwarded-For"
```


ip The cdn node is passed, you don't have to worry about this.

**Comment by f4nff** [comment] 2018-10-15 06:07
tls1.3+ALPN

**Comment by f4nff** [comment] 2018-10-17 20:14
When to solve it, for a great god like the author, it can be solved in a few minutes.

**Closed** 2018-10-18 00:10 UTC
Labels: bug
