### ISSUE TITLE
Redundancy of loading

### ISSUE THREAD

**Issue by YouROK** [anacrolix/torrent#253] opened 2018-05-31 19:21 UTC
When viewing a movie in an Elementum or in my program (similar to an Elementum https://github.com/YouROK/TorrServe), downloading useful data (BytesReadUsefulData) is ~20 times smaller than BytesReadData
Torrent 7.7 GB
In stat:
BytesRead ~9.57 GB
BytesReadData ~9.55 GB
BytesReadUsefulData ~564 MB

Therefore, the download of the network channel is very large

Sorry for my english, this is not my native language

**Comment by anacrolix** [comment] 2018-06-04 07:42
There's all manner of possible causes for this. Could you provide a way to reproduce the problem?

**Comment by YouROK** [comment] 2018-06-04 20:43
```
package main
import (
	"log"
	"os"
	"sync"
	"time"

	"github.com/anacrolix/torrent"
)

func main() {
	config := &torrent.Config{
		EstablishedConnsPerTorrent: 150,
		HalfOpenConnsPerTorrent:    97,
		DisableIPv6:                true,
	}

	client, err := torrent.NewClient(config)
	if err != nil {
		log.Fatal(err)
	}

	//Ubuntu
	t, err := client.AddMagnet("magnet:?xt=urn:btih:e4be9e4db876e3e3179778b03e906297be5c8dbe&dn=ubuntu-18.04-desktop-amd64.iso&tr=http%3a%2f%2ftorrent.ubuntu.com%3a6969%2fannounce&tr=http%3a%2f%2fipv6.torrent.ubuntu.com%3a6969%2fannounce")
	if err != nil {
		log.Fatal(err)
	}

	<-t.GotInfo()
	file := t.Files()[0]

	reader := file.NewReader()
	var wa sync.WaitGroup
	wa.Add(1)

	go func() {
		buf := make([]byte, 4*1024*1024)
		for {
			_, err := reader.Read(buf)
			if err != nil {
				break
			}
		}
		wa.Done()
	}()

	go func() {
		cl := t.Closed()
		for {
			select {
			case <-cl:
				return
			default:
				client.WriteStatus(os.Stdout)
			}
			time.Sleep(time.Second)
		}
	}()
	wa.Wait()
}
```

After a while: 185mb useful and 557mb of other
  BytesRead: (int64) 557242945,
  BytesReadData: (int64) 555204608,
  BytesReadUsefulData: (int64) 185155584,
The longer the loading, the greater the difference

Log:
Listen port: 46663
Peer ID: "-GT0001-\x1fy]@?\xea\xb0\x18%a<\xfd"
Announce key: 25613cfd
Banned IPs: 0
udp DHT server at 0.0.0.0:46663:
	# Nodes: 178 (119 good, 0 banned)
	Server ID: 83794b1d8750bd286fa9a9b397b17cdb4d81a71e
	Announces: 501
	Outstanding transactions: 0
\# Torrents: 1

ubuntu-18.04-desktop-amd64.iso
10.370844% of 842423846328 bytes (1.9 GB)
Infohash: e4be9e4db876e3e3179778b03e906297be5c8dbe
Metadata length: 73418
Piece length: 524288
Num Pieces: 3666 (379 completed)
Piece States: 377C 1!P 2C 1R 1RP 5R 3279
Reader Pieces: 377:387
Enabled trackers:
    URL                                             Next announce  Last announce
    "http://ipv6.torrent.ubuntu.com:6969/announce"  3m14s          error announcing: Get http://[2001:7b8:3:37::21:3]:6969/announce?compact=1&downloaded=0&info_hash=%E4%BE%9EM%B8v%E3%E3%17%97x%B0%3E%90b%97%BE%5C%8D%BE&left=18446744073709551615&peer_id=-GT0001-%1Fy%5D%40%3F%EA%B0%18%25a%3C%FD&port=46663&supportcrypto=1&uploaded=0: dial tcp [2001:7b8:3:37::21:3]:6969: connect: network is unreachable
    "http://torrent.ubuntu.com:6969/announce"       28m14s         50 peers

DHT Announces: 1
(torrent.TorrentStats) {
 ConnStats: (torrent.ConnStats) {
  BytesWritten: (int64) 3321558,
  BytesWrittenData: (int64) 0,
  BytesRead: (int64) 557242945,
  BytesReadData: (int64) 555204608,
  BytesReadUsefulData: (int64) 185155584,
  ChunksWritten: (int64) 0,
  ChunksRead: (int64) 33887,
  ChunksReadUseful: (int64) 11331,
  ChunksReadUnwanted: (int64) 22586,
  PiecesDirtiedGood: (int64) 352,
  PiecesDirtiedBad: (int64) 0
 },
 TotalPeers: (int) 611,
 PendingPeers: (int) 472,
 ActivePeers: (int) 48,
 ConnectedSeeders: (int) 48,
 HalfOpenPeers: (int) 97
}
 1. "-DE13F0-TZTP-PRfhcE8"                                  0000000000100005 10.0.0.10:39322-108.65.197.194:57941
    last msg: 0.04s ago, connected: 103.40s ago, last helpful: never, itime: 1m43.393098417s
    3666/3666 completed, 0 pieces touched, good chunks: 0/303-0 reqq: (32,46,64]-0, flags: i-ETr-, dr: 0.0 KiB/s
    next pieces: [386 382 383 380 377 381 384 385]
 ...
48. "-BT7a3S-\x8d\xad_\u11e9\x90\x05\x96I\xae\xf6"          0000000000100005 10.0.0.20:56212-46.188.53.213:21512
    last msg: 0.01s ago, connected: 31.71s ago, last helpful: 0.01s ago, itime: 31.707522913s
    3666/3666 completed, 1 pieces touched, good chunks: 2786/3238-0 reqq: (115,219,255]-0, flags: i-eHg-, dr: 1405.8 KiB/s
    next pieces: [377 380 381 382 383 384 385 386] (fastest)

**Comment by anacrolix** [comment] 2018-06-05 03:15
Excellent, thanks.

**Comment by anacrolix** [comment] 2018-06-08 13:01
I've started looking into it. I suspect that because your code is streaming directly from the Reader, you're getting a lot of overlap.

**Comment by spawnlmg** [comment] 2018-06-14 06:13
Are there any progress in this matter? What is the probability of getting rid of unnecessary traffic?

**Comment by anacrolix** [comment] 2018-06-14 09:06
I'm undecided on the right algorithm to avoid this. I began implementing some stuff that causes https://github.com/anacrolix/torrent/issues/249, I'm still not sure that's resolved.

**Comment by elgatito** [comment] 2018-06-17 10:34
@anacrolix maybe we can use an option for selection strategy? Like traffic-less mode, optimal, faster piece availability. Something like that.

**Comment by anacrolix** [comment] 2018-06-17 13:14
That's a good idea, I'll try that if I can't come up with something.

**Comment by spawnlmg** [comment] 2018-06-22 13:51
Due to excess traffic, which is several times more useful, it is not possible to watch a video with a bitrate of more than 40mbits per 100mbit network. To watch video with a bitrate of 50 mbit, you need a network speed of 200-250 mbit

**Comment by anacrolix** [comment] 2018-06-22 14:12
As a temporary workaround, if you have the available storage space, call `Torrent.DownloadAll`, or `File.Download` on the relevant file.

**Comment by spawnlmg** [comment] 2018-06-22 14:57
I'm interested in the use of RAM. The use of drives is not interesting.

**Comment by spawnlmg** [comment] 2018-06-22 15:02
Is there any way to correct this useless traffic?
Can you hope for an early fix?

**Comment by anacrolix** [comment] 2018-06-23 08:21
I'm currently working on a new algorithm.

**Comment by anacrolix** [comment] 2018-06-26 04:58
I've made a bunch of changes that should reduce the waste with the current algorithm. From testing, when streaming (i.e. reading from a torrent.Reader), as much as ~50-70% of traffic could be redundant. That number now seems to be 10-20%. I've also implemented an entirely new requesting algorithm, but it's not currently enabled (I will do more testing with it first). Chunks were being previously being discarded because the priorities had changed, this has been fixed, and the statistic that represents it has been updated to reflect the true value now measured: ChunksReadWasted. Please use https://github.com/anacrolix/torrent/commit/c921242f30364d3d03947455a5a88ac376059444 or later.

**Comment by anacrolix** [comment] 2018-06-26 05:01
If you want to try the newest algorithm in its present state, set requestStrategy to 3 here: https://github.com/anacrolix/torrent/blob/c921242f30364d3d03947455a5a88ac376059444/client.go#L974.

**Comment by YouROK** [comment] 2018-06-26 15:24
Panic when GotInfo() in 3 strategy:
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90ce2c]
> 
> goroutine 743 [running]:
> github.com/anacrolix/torrent/metainfo.(*Info).NumPieces(0x0, 0x0)
> 	/home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/metainfo/info.go:132 +0x1c
> github.com/anacrolix/torrent.(*Torrent).numPieces(0xc4200f2000, 0x0)
> 	/home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/torrent.go:689 +0x3d
> github.com/anacrolix/torrent.(*connection).iterUnbiasedPieceRequestOrder(0xc4201ec580, 0xc420f4b7a0, 0x0)
> 	/home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/connection.go:689 +0x447
> github.com/anacrolix/torrent.(*connection).iterPendingPieces(0xc4201ec580, 0xc420f4b7a0, 0xc420575c00)
> 	/home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/connection.go:743 +0x57
> github.com/anacrolix/torrent.(*connection).fillWriteBuffer(0xc4201ec580, 0xc420377220)
> 	/home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/connection.go:542 +0x17d
> github.com/anacrolix/torrent.(*connection).writer(0xc4201ec580, 0xdf8475800)
> 	/home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/connection.go:604 +0x3b1
> created by github.com/anacrolix/torrent.(*Client).runHandshookConn
> 	/home/yourok/Space/Projects/Android/TorrServe/TorrServer/src/github.com/anacrolix/torrent/client.go:803 +0x704
 
Temporary fixed:
```
func (t *Torrent) numPieces() int {
	if !t.haveInfo() {
		return 0
	}
	return t.info.NumPieces()
}
```

**Comment by anacrolix** [comment] 2018-06-28 02:05
I've committed a fix for that @YouROK . Further testing is showing that "wastage" was about 68% (~3mbps required for a 1mbps stream), with the improvements to chunk handling it's down to 40% (1.67mbps required for 1 mbps stream). With requestStrategy 3, I'm seeing wastage of less than 1%. (1mbps for 1 mbps).

**Closed** 2018-06-28 02:06 UTC
Labels: enhancement
