### ISSUE TITLE
Seeding doesn't work

### ISSUE THREAD

**Issue by themihai** [anacrolix/torrent#193] opened 2017-09-16 08:02 UTC
For some reasons the client is not seeding anything even after the download is long completed. Any idea what might cause that? The seeding in a regular client (i.e. uTorrent) seems to work just fine with the same torrent. Firewall is off. 
```
	cfg := &torrent.Config{
		Seed:       true,
		ListenAddr: ":0",
		DHTConfig: dht.ServerConfig{
			StartingNodes: dht.GlobalBootstrapAddrs,
		},
	}
	c, err := torrent.NewClient(cfg)
	if err != nil {
		return nil, err
	}
	to, err := c.AddMagnet(magnetLink)
	if err != nil {
		c.Close()
		return nil, err
	}
       go func(){
           for{
	          st := to.Stats()
	          fmt.Printf("r %v, w %v",  st.DataBytesRead, st.DataBytesWritten)
                  time.Sleep(1 * time.Second)
          }
       }()
``` 

Result:
```
read 81988700, write 0
read 331074652, write 0
read 585960540, write 0
read 841665628, write 0
read 1097813084, write 0
........................................
read 15332346972, write 0
read 15332346972, write 0
```

**Comment by anacrolix** [comment] 2017-09-16 09:48
What git revision are you using? Is the data for the torrent marked as complete?

**Comment by themihai** [comment] 2017-09-16 10:24
rev is 5d3ee0a53149b7d07288dbe3dcc4bc417cbc919b . How do I check if the data for the torrent is  marked as complete?

**Comment by anacrolix** [comment] 2017-09-16 12:02
The decision on whether to seed is made here: https://github.com/anacrolix/torrent/blob/master/torrent.go#L1116. You can check the Client WriteStatus to see what the client is doing for given torrents. There are a bunch of unit tests that test seeding, so check those out as well.

**Comment by pepesi** [comment] 2017-10-10 02:57
I have a file.zip.torrent file and it's corresponding file(file.zip) in the same directory.
When I use rev 17ea4f7fdd2b73bc32e855d4670bbeacdda5c713, `go run cmd/torrent/main.go file.zip.torrent` always be 0% downloaded and `-seed=true` not working. 
When I use rev 885c88451b3c6a831befbb8e20414be2ebef9193, it works well. 
So I think there may be a bug  17ea4f7fdd2b73bc32e855d4670bbeacdda5c713

**Comment by anacrolix** [comment] 2017-10-10 04:36
@pepesi , I don't find the commit 885c88451b3c6a831befbb8e20414be2ebef9193. Can you check this again?

**Comment by pepesi** [comment] 2017-10-10 04:58
Sorry， i made a mistake. isn't 885c88451b3c6a831befbb8e20414be2ebef9193.
firstly, I checkout 881f1a7e35f4d738f8ebea6d9c5e78cccc7cebb4, then cherry-pick  2c91d1e3fbd2b8e9dc1f42d2a3f8398081c2c60b.

**Comment by pepesi** [comment] 2017-10-10 05:18
Sorry, rev 885c88451b3c6a831befbb8e20414be2ebef9193 is my local commit.

I think the problem is rev 2aa20b3e222e218541b30d9e063cd2e3c855e9ca, I tested b39df82fbc9269c69257ac22dea87338a886faf6 works but rev 2aa20b3e222e218541b30d9e063cd2e3c855e9ca not.

**Comment by pepesi** [comment] 2017-10-10 05:18
Sorry, rev 885c88451b3c6a831befbb8e20414be2ebef9193 is my local commit.

I think the problem is rev 2aa20b3e222e218541b30d9e063cd2e3c855e9ca, I tested b39df82fbc9269c69257ac22dea87338a886faf6 works but rev 2aa20b3e222e218541b30d9e063cd2e3c855e9ca not.

**Comment by anacrolix** [comment] 2017-10-10 05:49
The change requires that VerifyData be called for anything not downloaded through this implementation. This is the source of @pepesi's issue. I'm not sure if this is the same thing @themihai has run into.

**Comment by pepesi** [comment] 2017-10-10 05:56
I see, I have to call VerifyData before call DownloadAll . thanks

**Comment by anacrolix** [comment] 2017-10-10 12:39
I'm not happy with the way data is automatically verified. It's a hard balance between aggressively verifying whenever torrents are added, and never verifying unless requested.

**Comment by anacrolix** [comment] 2017-10-11 10:04
Thank you for contributing @pepesi . I think I have a fix that will give the best of all worlds. Do you have any update on your situation @themihai ?

**Comment by anacrolix** [comment] 2017-10-12 06:53
This is fixed.

**Closed by anacrolix** 2017-10-12 06:53 UTC
