### ISSUE TITLE
invalid memory address or nil pointer dereference in request-strategy.(*PieceRequestOrder).Update

### ISSUE THREAD

**Issue by vintikzzz** [anacrolix/torrent#795] opened 2022-12-22 08:42 UTC
Hi!

Got this today:
```
2022-12-22T06:46:18+0000 ERR [main client github.com/anacrolix/torrent.(*Peer).receiveChunk:1526]: *torrent.PeerConn 0xc02959a900 [id="-UT360W-\xfe\xb5\xe6y\xc9_\xd0\xe4JVy\x84", exts=0000000000100005, v="μTorrent 3.6"]: writing received chunk 484874: short write
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc69ad5]

goroutine 12618781 [running]:
github.com/anacrolix/torrent/request-strategy.(*PieceRequestOrder).Update(0x0, {{0x48, 0x52, 0x39, 0x69, 0x9c, 0x80, 0x1d, 0xf5, 0x8, ...}, ...}, ...)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/request-strategy/piece-request-order.go:55 +0x55
github.com/anacrolix/torrent.(*Torrent).updatePieceRequestOrder(0xc02cded500, 0x3b3)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/torrent-piece-request-order.go:11 +0xe9
github.com/anacrolix/torrent.(*Piece).pendChunkIndex(0xc03b255208, 0x1?)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/piece.go:90 +0x57
github.com/anacrolix/torrent.(*Torrent).pendRequest(0x1?, 0x82c300?)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/torrent.go:1275 +0x50
github.com/anacrolix/torrent.(*Peer).receiveChunk(0xc02959a900, 0xc03b336a80)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/peerconn.go:1527 +0xb85
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc02959a900)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/peerconn.go:1255 +0x985
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc0009ee000, 0xc02959a900, 0xc02cded500)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/client.go:994 +0x4a5
github.com/anacrolix/torrent.(*Torrent).logRunHandshookConn(0xc02cded500, 0xc02cded500?, 0x0, {0x14?})
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/torrent.go:1615 +0x52
github.com/anacrolix/torrent.(*Torrent).runHandshookConnLoggingErr(...)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/torrent.go:1622
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc0009ee000, 0x443a25?, {0x1538980?, 0xc01ebd9be0}, {0x11d5e6a, 0x2}, 0x0)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/client.go:797 +0x3bb
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	/go/pkg/mod/github.com/anacrolix/torrent@v1.47.0/torrent.go:2269 +0x25d
```

**Comment by anacrolix** [comment] 2022-12-25 08:04
Wow, thanks for the report, I can reproduce this.

**Comment by anacrolix** [comment] 2022-12-25 21:55
Could you try with v1.48.0, which includes https://github.com/anacrolix/torrent/commit/f75989863cfc4abfc14c1b4ab9a634437569ef27?

**Comment by vintikzzz** [comment] 2022-12-25 22:05
This tag is not available, can you push it?
```
go get -u 'github.com/anacrolix/torrent@v1.48.0'
go: github.com/anacrolix/torrent@v1.48.0: invalid version: unknown revision v1.48.0
```

**Comment by vintikzzz** [comment] 2022-12-25 22:12
can't build project after update
```
go build .
# github.com/anacrolix/dht/v2/k-nearest-nodes
../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/k-nearest-nodes/k-nearest-nodes.go.go:21:9: cannot use generic type immutable.SortedMap[K comparable, V any] without instantiation
../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/k-nearest-nodes/k-nearest-nodes.go.go:29:33: type lessComparer of lessComparer{…} does not match immutable.Comparer[K] (cannot infer K and V)
# github.com/anacrolix/dht/v2/containers
../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/containers/addr-maybe-ids-by-distance.go:21:6: cannot use generic type stmutil.Settish[K stmutil.KeyConstraint] without instantiation
../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/containers/addr-maybe-ids-by-distance.go:42:47: interface{} does not implement comparable
```

**Comment by anacrolix** [comment] 2022-12-26 00:14
Thanks, I've pushed `v1.48.0`.

**Comment by anacrolix** [comment] 2022-12-26 00:22
> can't build project after update
> 
> ```
> go build .
> # github.com/anacrolix/dht/v2/k-nearest-nodes
> ../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/k-nearest-nodes/k-nearest-nodes.go.go:21:9: cannot use generic type immutable.SortedMap[K comparable, V any] without instantiation
> ../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/k-nearest-nodes/k-nearest-nodes.go.go:29:33: type lessComparer of lessComparer{…} does not match immutable.Comparer[K] (cannot infer K and V)
> # github.com/anacrolix/dht/v2/containers
> ../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/containers/addr-maybe-ids-by-distance.go:21:6: cannot use generic type stmutil.Settish[K stmutil.KeyConstraint] without instantiation
> ../../../../go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.2/containers/addr-maybe-ids-by-distance.go:42:47: interface{} does not implement comparable
> ```

Either `go get github.com/anacrolix/dht/v2@master`, or ensure that your indirect dependencies on github.com/anacrolix/stm and github.com/benbjohnson/immutable aren't ahead of those declared by github.com/anacrolix/dht/v2 and github.com/anacrolix/torrent. It's likely you've upgraded anacrolix/dht/v2 at some point, then downgraded again.

**Comment by vintikzzz** [comment] 2022-12-26 07:27
> Either go get github.com/anacrolix/dht/v2@master

Thanks for advice, it builds right now!
We have to wait for a day to check.

**Comment by vintikzzz** [comment] 2022-12-27 07:14
@anacrolix I have checked logs last day. The issue seems to be resolved! Great job! 👍

**Comment by anacrolix** [comment] 2022-12-28 02:49
Thanks @vintikzzz

**Comment by vintikzzz** [comment] 2023-02-01 19:20
@anacrolix Hi! This issue still persists.

**Comment by anacrolix** [comment] 2023-02-03 02:33
I haven't had time to look into this. Do I recall correctly that you were setting very large chunk sizes in your project?

**Comment by vintikzzz** [comment] 2023-02-03 08:22
@anacrolix no, settings are quite usual
```golang
cfg := torrent.NewDefaultClientConfig()
cfg.NoUpload = true
cfg.Seed = false
cfg.DefaultStorage = NewMMap(s.dataDir)
cfg.DisableUTP = true
cfg.DisableWebtorrent = true
cfg.EstablishedConnsPerTorrent = 100
cfg.HalfOpenConnsPerTorrent = 50
cfg.TorrentPeersHighWater = 1000
cfg.TorrentPeersLowWater = 100
cfg.TotalHalfOpenConns = 5000
```
I've already forked your project and done the fix. I have to do some trials during weekends. If everything will be fine, I will do a pull request on Monday.

**Comment by vintikzzz** [comment] 2023-02-05 12:50
made a PR #807

**Comment by anacrolix** [comment] 2023-02-06 02:15
Interesting, the PR got me thinking. Is it possible the torrent has been closed while the chunk is processed? It looks like that the torrent has been removed from the piece request order store in the Client.

**Comment by vintikzzz** [comment] 2023-02-06 07:21
It is quite possible, I also thought about it. In my use case, I delete torrents from a client that were not used for a specific period of time.

**Comment by anacrolix** [comment] 2023-02-06 11:34
I do the same thing, but it's interesting I haven't seen the bug. I think there's a better fix checking if it torrent is closed in receiveChunk.

**Comment by anacrolix** [comment] 2023-05-19 04:24
The place the panic occurs is the only code path to place you fixed in your PR. So I think it's the best fix for now. Thank you!

**Closed** 2023-05-19 04:23 UTC
Labels: confirmed
