### ISSUE TITLE
Can't use gorm because the change of crawshaw.io/sqlite

### ISSUE THREAD

**Issue by hichenming** [anacrolix/torrent#421] opened 2020-07-31 09:27 UTC
torrent has changed sqlite library to use crawshaw.io/sqlite in this commit https://github.com/anacrolix/torrent/commit/7455b98a0f597c3b84c7ed60b75b9ddf5fd8d341

I use gorm to manage database, and gorm needs sql diver github.com/mattn/go-sqlite3, as a result, I can't compile my project now：

```
duplicate symbol _sqlite3_prepare16_v2 in:
    /var/folders/24/0wn_ks8j15375jy_t4tycjf40000gn/T/go-link-184254381/000029.o
    /var/folders/24/0wn_ks8j15375jy_t4tycjf40000gn/T/go-link-184254381/000059.o
ld: 240 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there a workround that we can choose which sqlite lib to use? Maybe add some build flag?

Thanks advance, nice work anyway.

**Comment by anacrolix** [comment] 2020-08-03 01:29
@hichenming oh dear, this is tricky. Are you aware of a way to allow both to be linked together? If not, I think a tag is the right way forward, as you suggest.

**Comment by ZelAk312** [comment] 2020-10-06 12:42
I had the same issue. After searching for many hours I didn't find a way to link them together or anything but I found a way to make it work by allowing multiple definitions with this flag `-ldflags "-extldflags=-Wl,--allow-multiple-definition"`. I don't think it's the best solution to be hones, it feels more like a workaround.

**Comment by anacrolix** [comment] 2020-11-11 23:31
@ZelAk312 @hichenming do you want to try with running `go mod edit -replace crawshaw.io/sqlite=github.com/getlantern/sqlite`? There should be a [fix](https://github.com/crawshaw/sqlite/pull/103) in there that solves this issue. Please let me know if it works for you.

**Comment by ZelAk312** [comment] 2020-11-15 21:40
I tried running after using the command, it still fails to compile and it did create the replace in the go.mod file
```
/usr/bin/ld: /tmp/go-link-071491094/000052.o: in function `sqlite3_rtree_query_callback':
/home/zelak/go/pkg/mod/github.com/getlantern/sqlite@v0.3.2/./c/sqlite3.c:193496: multiple definition of `sqlite3_rtree_query_callback'; /tmp/go-link-071491094/000028.o:/home/zelak/go/pkg/mod/github.com/mattn/go-sqlite3@v2.0.3+incompatible/sqlite3-binding.c:192344: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by anacrolix** [comment] 2020-11-16 01:28
@ZelAk312 thanks

**Comment by skinner12** [comment] 2020-11-26 15:14
I have the same error and I can't update from 1.15.2 to 1.18.1 and I've tried `go mod edit -replace crawshaw.io/sqlite=github.com/getlantern/sqlite@v0.3.2` but still the same error

**Comment by anacrolix** [comment] 2020-11-28 22:21
@skinner12 @ZelAk312 @hichenming could you confirm that you're using github.com/mattn/go-sqlite3 elsewhere in your application? It's nothing internal to anacrolix/torrent that is using it?

I thought the fix in github.com/getlantern/sqlite would fix this issue, but then ran into it myself with another application I have that used mattn/go-sqlite3 throughout, and tried to use a recent anacrolix/torrent that was using crawshaw.io/sqlite.

I'm not sure what the best way forward is, I expect a tag and/or something linker related is required. I'm not sure it's reasonable to expect anacrolix/torrent to revert to mattn/go-sqlite3, just because that's the most popular module for sqlite3 in Go. It could be possible to break out some of the sqlite stuff in anacrolix/torrent into modules that aren't always depended on, or provide a tag to exclude that stuff so that another sqlite module can be used.

**Comment by skinner12** [comment] 2020-11-28 23:15
Hi @anacrolix, I **confirm** that I'm using _sqlite3_ elsewhere: I used it for save some infos from downloading torrents and other data.

Anyway, now that my app gets bigger, I choose to use _postgresql_ so I didn't get _sqlite3_ dependence, the error disappears and I **updated** to latest version of anacrolix/torrent seamless. 

**Thanks** for your support

**Comment by anacrolix** [comment] 2020-11-30 02:56
Thanks for the feedback @skinner12 .

**Comment by anacrolix** [comment] 2020-11-30 03:18
When crawshaw.io/sqlite and mattn/go-sqlite3 are in the same binary, try passing `libsqlite3` in the build `-tags` option. This will only build sqlite3 once using crawshaw.io/sqlite's implementation. For example, when running tests in my package I'm able to do `$ go test -tags libsqlite3 ./...`. Thanks to https://github.com/joesis for finding this.

**Comment by anacrolix** [comment] 2021-01-19 21:18
This should be fixed with https://github.com/anacrolix/torrent/issues/421#issuecomment-735521392.

**Closed by anacrolix** 2021-01-19 21:18 UTC

**Comment by racoon-devel** [comment] 2023-03-31 14:19
I have the same issue. And mentioned solution doesn't work... 
```
go get -u gorm.io/gorm
go get -u gorm.io/driver/sqlite
```

After it:

```
$ go build -tags libsqlite3 ./rms-torrent.go                                                                                                               
# github.com/anacrolix/missinggo/v2/conntrack
../../../go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.7.0/conntrack/instance.go:24:16: cannot use generic type stm.Var[T any] without instantiation
../../../go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.7.0/conntrack/instance.go:25:16: cannot use generic type stm.Var[T any] without instantiation
../../../go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.7.0/conntrack/instance.go:29:11: cannot use generic type stm.Var[T any] without instantiation
../../../go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.7.0/conntrack/instance.go:32:21: cannot use generic type stm.Var[T any] without instantiation
../../../go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.7.0/conntrack/instance.go:33:21: cannot use generic type stm.Var[T any] without instantiation

```

**Comment by anacrolix** [comment] 2023-04-03 01:18
@racoon-devel I am not able to reproduce this. Could you provide a link to your project so I can try build it?

**Comment by racoon-devel** [comment] 2023-04-03 15:14
> @racoon-devel I am not able to reproduce this. Could you provide a link to your project so I can try build it?

Sure, branch `feature/advanced-torrent`
https://github.com/RacoonMediaServer/rms-torrent/tree/feature/advanced-torrent

**Comment by anacrolix** [comment] 2023-04-05 04:58
I pushed a fix to https://github.com/anacrolix/rms-torrent/tree/feature/advanced-torrent.

For some reason your anacrolix/torrent is stuck on v1.11.0. This happens frequently, it's a combination of https://github.com/golang/go/issues/55955 and https://github.com/golang/go/issues/56494 making it nontrivial to upgrade.

You should find it's fixed if you incorporate the changes in the branch above, and ensure that anacrolix/torrent does not regress to v1.11.0.

**Comment by racoon-devel** [comment] 2023-04-05 08:42
Oh... @anacrolix Thank you so much!
